name: Another Workflow

on:
  workflow_dispatch:

jobs:
  my-remote-job:
   outputs:
      logoutput: ${{ steps.logstep.outputs.log }}
   runs-on: ubuntu-latest
   steps:
      - name: Conclussion step that can handle the result
        id: stepid        
        run:  echo "log=annamalai" >> $GITHUB_OUTPUT
        
      - name: Use prior output
        run: echo "The log was ${{ steps.stepid.outputs.log }}"
