name: Another Workflow

on:
  workflow_dispatch:

jobs:
  my-remote-job:
   outputs:
      logoutput: ${{ steps.logstep.outputs.log }}
   runs-on: ubuntu-latest
   steps:
      - name: Conclussion step that can handle the result
        id: conclusionstep        
        run:  echo "log=annamalai" >> $GITHUB_OUTPUT
