name: Another Workflow

on:
  workflow_dispatch:
    inputs:
      run-name:
        description: 'The distinct run name used to retrieve the run ID. Defaults to the workflow name'
        type: string
        required: false

jobs:
  my-remote-job:
   runs-on: ubuntu-latest
   steps:
      - name: scrapoutput
        run: |
         echo "The value of the variable is:${{ inputs.run-name }}"
         echo "winsip3upsuccess"    
