
name: Another Workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    
  workflow_dispatch:
    inputs:
      run-name:
        description: 'The distinct run name used to retrieve the run ID. Defaults to the workflow name'
        type: string
        required: false

jobs:
 example_job:
    name: Generate output
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "xRunId1y"      
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

      - id: get-id
        uses: actions/github-script@0.9.0
        with:
          script: |
            const id = 'runid100'
            core.setOutput('id', id)
            core.setOutput('workflow-id',id)
            core.exportVariable("ID_TOKEN", id);
      - run: |
            echo "${{steps.get-id.outputs.id}}"
            echo "${{steps.get-id.outputs.workflow-id}}"
            echo ${{ env.ID_TOKEN }}

