name: Another Workflow

on:
  workflow_dispatch:
    inputs:
      run-name:
        description: 'The distinct run name used to retrieve the run ID. Defaults to the workflow name'
        type: string
        required: false

jobs:
  my-remote-job:
   runs-on: ubuntu-latest
   outputs:
      job-status: ${{ steps.joboutputstep.outputs.runid }} 
   steps:
      - name: scrapoutput
      - id: joboutputstep
        run: |
         echo "The value of the variable is:${{ inputs.run-name }}"
         echo "winsip3upsuccess"    
         echo "::set-output name=runid::12"
