name: Another Workflow

on:
  workflow_dispatch:

jobs:
  my-remote-job:
   runs-on: ubuntu-latest
   steps:
      - name: scrapoutput
        run: 
         echo "Hello world!"
         echo "::set-output name=response::Processed data"
