name: Another Workflow

on:
  workflow_dispatch:

jobs:
  my-remote-job:
   runs-on: ubuntu-latest
   steps:
      - name: scrapoutput
        run: |
         echo "The value of the variable is:${{ inputs.myInput }}"
         echo "winsip3upsuccess"    
