
name: Another Workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    
  workflow_dispatch:
    inputs:
      run-name:
        description: 'The distinct run name used to retrieve the run ID. Defaults to the workflow name'
        type: string
        required: false

jobs:
 example_job:
    name: Generate output
    runs-on: ubuntu-latest
    if: github.event.action != 'Trigger Workflow1'
    steps:
      - id: step1
        run: |
          echo "xRunId1y"      
          curl -X POST https://api.github.com/repos/annamalaiponnusamy/repo_01/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow1", "client_payload": { "repository": "test" }}'     
